### PR TITLE
Add rotary encoder

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by ubruhin** [comment]
A slightly more expressive symbol would be nice, maybe like this one in KiCad?
grafik

**Comment by dbrgn** [comment]
@ubruhin like this?

img

**Comment by ubruhin** [comment]
Looks good, although I'd prefer to have the pins at the left side :grin:

And as discussed offline, it would be nice to have both symbol variants, one with the switch integrated into the encoder symbol and one with separate encoder and switch symbols (but we could still add that second symbol variant later).

**Comment by dbrgn** [comment]
@ubruhin I moved the pins to the left and created a second symbol variant with integrated switch.

**Pull request merged**
