### PR TITLE
Add SSOP packages

### PR DESCRIPTION
**Pull request by dbrgn**
Generated with parts-generator, see LibrePCB/librepcb-parts-generator#48.

Based on JEDEC MO-150 and MO-152.

PR based on #33, merge that first.

### CODE REVIEW

**Comment by dbrgn** [comment]
Ready for review now, @ubruhin!

**Comment by ubruhin** [comment]
Some of the packages are named "TSSOP" - that's a mistake, isn't it?

**Comment by dbrgn** [comment]
> Some of the packages are named "TSSOP" - that's a mistake, isn't it?

Yes, it's a mistake!

**Comment by dbrgn** [comment]
@ubruhin should be fixed now.

**Comment by dbrgn** [comment]
UUIDs are updated for compatibility with the FTDI PR 1 and the numbers are now rounded to 3 decimal places.

**Comment by dbrgn** [comment]
Package UUID is now adjusted too.

**Comment by dbrgn** [comment]
:tada: thanks for the review.

**Pull request merged**
