### PR TITLE
Use IPC conforming names for SOIC packages

### PR DESCRIPTION
**Pull request by dbrgn**
Follow-up of #8, refs https://github.com/LibrePCB/librepcb-parts-generator/pull/18.

Updated SOIC packages with IPC conforming names.

Old packages have been remapped where applicable:

```diff
--- a/pkg/c1052243-2ebb-41ae-b287-c29094d0eee4/package.lp
+++ b/pkg/c1052243-2ebb-41ae-b287-c29094d0eee4/package.lp
@@ -1,10 +1,10 @@
 (librepcb_package c1052243-2ebb-41ae-b287-c29094d0eee4
- (name "SOIC-28 JEDEC 6.00mm")
- (description "28-lead 6.00mm wide Small Outline Integrated Circuit (JEDEC SOIC)\n\nGenerated with librepcb-parts-generator (generate_soic.py)")
+ (name "SOIC127P600X175-28")
+ (description "28-pin Small Outline Integrated Circuit (SOIC), standardized by JEDEC.\n\nPitch: 1.27 mm\nNominal width: 6.00mm\nHeight: 1.75mm\n\nGenerated with librepcb-parts-generator (generate_so.py)")
  (keywords "soic28,so28,so,soic,small outline,smd,jedec")
  (author "Danilo B.")
  (version "0.1")
- (created 2018-11-09T20:27:23Z)
+ (created 2018-11-09T23:32:56Z)
  (deprecated false)
  (category a074fabf-4912-4c29-bc6b-451bf43c2193)
  (pad 8ea5f678-65a5-48a1-b960-811db67ec930 (name "1"))
@@ -363,7 +363,7 @@
    (vertex (position -1.95 9.055) (angle 0.0))
   )
   (circle be23bd36-dc91-4365-bfd2-1dd9513be8aa (layer top_placement)
-   (width 0.0) (fill true) (grab_area false) (diameter 0.787) (position -1.163 8.268)
+   (width 0.0) (fill true) (grab_area false) (diameter 0.635) (position -0.997 8.26)
   )
   (stroke_text c0053250-894f-4b17-bba3-dd73477c4799 (layer top_names)
    (height 1.0) (stroke_width 0.2) (letter_spacing auto) (line_spacing auto)
@@ -704,7 +704,7 @@
    (vertex (position -1.95 9.055) (angle 0.0))
   )
   (circle 85aab861-bc6a-4ae4-8d85-f3b9a8f0f373 (layer top_placement)
-   (width 0.0) (fill true) (grab_area false) (diameter 0.787) (position -1.163 8.268)
+   (width 0.0) (fill true) (grab_area false) (diameter 0.635) (position -0.997 8.26)
   )
   (stroke_text db41a6d8-d4ee-42a6-b07c-97b8ce1fe166 (layer top_names)
    (height 1.0) (stroke_width 0.2) (letter_spacing auto) (line_spacing auto)
```

One package has been deleted (EIAJ 48 pin), since the spec does not actually include 48 pin packages. I think we can safely assume that nobody started using that UUID already :wink: 

Version hasn't been updated, I don't think that's important at this stage.

screenshot1

screenshot2

(Last screenshot has a pin1 dot that's still too big, that has since been fixed.)

### CODE REVIEW

**Comment by dbrgn** [comment]
The IPC-7351B naming convention can be found here: https://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/IPC-7x51 & PCBM Land Pattern Naming Convention.pdf

**Comment by ubruhin** [comment]
Waht's the difference between SOIC127P762 and SOIC127P1524? Their footprints are exactly identical, but "nominal width" is different?

**Comment by dbrgn** [comment]
Oh, they shouldn't be identical. That's a bug, thanks for spotting!

**Comment by dbrgn** [comment]
Fixed in https://github.com/LibrePCB/librepcb-parts-generator/commit/907a3cfe4230584c00bd59142a9cb6de3b69e0e0.

Note: I removed 7.62mm wide parts with more than 32 leads and 15.24mm wide parts with less than 20 leads. They seem improbably to me.

**Comment by dbrgn** [comment]
Whaat? :joy: :joy: :joy: 

Can't be, you must have been dreaming :running_man: 

(I forgot to git-reset the pkg directory after deleting the old packages...)

**Pull request merged**
